name: Push to main branch

on:
  push:
    branches:
      - main
jobs:
  ms3_review:
    if: (github.actor != 'ms3-bot' && github.event.pusher.name != 'github-actions[bot]')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout corpus repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MS3_BOT_TOKEN }}
          path: ${{ github.event.repository.name }}

      - name: Run 'ms3 review' via dcml_corpus_workflow action
        uses: DCMLab/dcml_corpus_workflow@v2.5.6 # Uses an action in the root directory
        id: act_docker
        with:
          ms3-command: "push_to_main"
        env:
          Token: "${{ secrets.MS3_BOT_TOKEN }}"
          commitFrom: "${{ github.event.before }}"
          comment_msg: ""
          directory: "${{ github.workspace }}"
          working_dir: ${{ github.event.repository.name }}

  corpus_stats:
    runs-on: ubuntu-latest
    steps:
    
      - name: Clone corpusstats
        uses: actions/checkout@v2
        with:
          repository: DCMLab/corpus_statistics_generator
          path: ./corpusstats
          ref: main
          token: ${{ secrets.MS3_BOT_MAINTENANCE  }}
      - name: Install corpusstats
        run: python -m pip install -e ./corpusstats
      - name: Generate GitHub pages
        working-directory: ./main
        run: |
          python .github/workflows/update_pages.py -g ${{ github.repository }} -t ${{ secrets.MS3_BOT_MAINTENANCE  }} -o ../public
      - name: Display generated files
        working-directory: ./public
        run: ls
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: true